String sessionId = "";
String accessToken = "";
String refreshToken = "";
String uniqueCode = "";
String userData = "";
String appLanguage = "";
String mitraLanguage = "";
String? fcmToken;
double? destLat;
double? destLong;
